### PR TITLE
Remove unexpected --write flag from prettier script

### PR DESCRIPTION
**Pull request by Zoe7**
Hi there!

I was copy-pasting these scripts in one of my own projects for ease of setup when I noticed a sneaky little `--write ` flag that formatted all my files when running `check-format` 😄

Thanks for making all these awesome courses btw!

### CODE REVIEW

**Comment by nickmccurdy** [comment]
I believe it's intentional that `--write` is used so you can `npm run prettier` and format the whole project. Without it you'd see the entire project printed out with formatting, which isn't very useful. However I don't believe Prettier's `--list-different` flag actually overrides `--write`, which is causing this issue.

I think a safer approach would be to have a separate Prettier script without either flag, with one version using `--write` and another using `--list-different`.

**Comment by kentcdodds** [comment]
Agreed @nickmccurdy.

I'm planning on an update of the course soon and I may adjust how this bit works. For now I need to leave the code as it is in the videos. Thanks anyway!

**Comment by Zoe7** [comment]
Hi again!

Unless I am going bananas, the videos don't have the `--write` flag in the prettier script, since it's only used to isolate the prettier logic so that we can run the `format` and `check-format` ones instead.
It's introduced in video 10 called "Validate All Files are Properly Formatted with Prettier"
and the diff for the code [is this one](https://github.com/kentcdodds/static-testing-tools/compare/tjs/step-06...tjs/step-07), which doesn't include the `--write` flag either. 

I also doubled-check the last video to be sure nothing had changed in between, and that one doesn't have the `--write` flag either in the prettier command (nor is it in the diff).
Looking at the different branches, it seems like it's introduced in the branch `step-14`, which seems to be very different from the other steps (lots of different commits).

I'm happy to drop this if you're going to update the course soon anyway, but I wanted to be sure that I am in fact not going crazy 😄

**Comment by kentcdodds** [comment]
Doh! You're right!

giphy (32)

Thanks!

**Pull request merged**
